In [53]:
# Task-1

"""
Create a Python program that converts between different units of measurement.
The program should:
. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
. Ask the user to input the value to be converted.
. Perform the conversion and display the result.
. Handle potential errors, such as invalid input or unsupported conversion types.
"""

def convert_units(conversion_type, value):

    if conversion_type == "m_to_ft":
        return value * 3.28084
    elif conversion_type == "ft_to_m":
        return value / 3.28084
    elif conversion_type == "kg_to_lbs":
        return value * 2.20462
    elif conversion_type == "lbs_to_kg":
        return value / 2.20462
    elif conversion_type == "l_to_gal":
        return value * 0.264172
    elif conversion_type == "gal_to_l":
        return value / 0.264172
    else:
        raise ValueError("Unsupported conversion type")


def main():
    try:
        print("Choose conversion type:")
        print("1. Meters to Feet")
        print("2. Feet to Meters")
        print("3. Kilograms to Pounds")
        print("4. Pounds to Kilograms")
        print("5. Liters to Gallons")
        print("6. Gallons to Liters")

        choice = input("Enter your choice (1-6): ")
        value = float(input("Enter the value to convert: "))

        conversion_map = {
            "1": "m_to_ft",
            "2": "ft_to_m",
            "3": "kg_to_lbs",
            "4": "lbs_to_kg",
            "5": "l_to_gal",
            "6": "gal_to_l"
        }

        if choice in conversion_map:
            result = convert_units(conversion_map[choice], value)
            print("Converted Value:", result)
        else:
            print("Invalid choice!")

    except ValueError:
        print("Error: Please enter a valid numeric value.")


if __name__ == "__main__":
    main()

Choose conversion type:
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Enter your choice (1-6): 3
Enter the value to convert: 62
Converted Value: 136.68643999999998


In [54]:
#Task-2

'''
Create a Python program that performs various mathematical operations on a list of numbers.
The Program should:
. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
. Ask the user to input a list of numbers (separated by spaces).
. Perform the selected operation and display the result.
. Handle potential errors, such as invalid input or empty lists.
'''


def find_sum(numbers):
    """
    Returns the sum of numbers in the list.
    """
    return sum(numbers)


def find_average(numbers):
    """
    Returns the average of numbers in the list.
    """
    return sum(numbers) / len(numbers)


def find_max(numbers):
    """
    Returns the maximum value in the list.
    """
    return max(numbers)


def find_min(numbers):
    """
    Returns the minimum value in the list.
    """
    return min(numbers)


def main():
    try:
        nums = input("Enter numbers separated by space: ")
        numbers = [float(x) for x in nums.split()]

        if len(numbers) == 0:
            raise ValueError("List is empty")

        print("\nChoose operation:")
        print("1. Sum")
        print("2. Average")
        print("3. Maximum")
        print("4. Minimum")

        choice = input("Enter choice: ")

        if choice == "1":
            print("Sum:", find_sum(numbers))
        elif choice == "2":
            print("Average:", find_average(numbers))
        elif choice == "3":
            print("Maximum:", find_max(numbers))
        elif choice == "4":
            print("Minimum:", find_min(numbers))
        else:
            print("Invalid choice!")

    except ValueError:
        print("Error: Please enter valid numeric values.")


if __name__ == "__main__":
    main()

Enter numbers separated by space: 2 4 6 8 10

Choose operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter choice: 1
Sum: 30.0


List Manipulation

In [27]:
#Extract Every Other Element:
#Write a Python function that extracts every other element from a list, starting from the first element.

def extract_every_other(lst):

    return lst[::2]


print(extract_every_other([1,2,3,4,5,6]))

[1, 3, 5]


In [28]:
#2. Slice a Sublist:
#Write a Python function that returns a sublist from a given list, starting from a specified index and
#ending at another specified index.


def get_sublist(lst, start, end):

    return lst[start:end+1]


print(get_sublist([1,3,5,7,9,11],2,4))

[5, 7, 9]


In [29]:
#3. Reverse a List Using Slicing:
#Write a Python function that reverses a list using slicing.


def reverse_list(lst):

    return lst[::-1]


print(reverse_list([1,2,3,4,5]))

[5, 4, 3, 2, 1]


In [30]:
#4. Remove the First and Last Elements:
#Write a Python function that removes the first and last elements of a list and returns the resulting
#sublist.


def remove_first_last(lst):

    return lst[1:-1]


print(remove_first_last([1,2,3,4,5]))

[2, 3, 4]


In [57]:
#5. Get the First n Elements:
#Write a Python function that extracts the first n elements from a list.


def get_first_n(lst, n):

    return lst[:n]


print(get_first_n([1,2,3,4,5],3))

[1, 2, 3]


In [56]:
#6. Extract Elements from the End:
#Write a Python function that extracts the last n elements of a list using slicing.


def get_last_n(lst, n):

    return lst[-n:]


print(get_last_n([1,2,3,4,5],2))

[4, 5]


In [55]:
#7. Extract Elements in Reverse Order:
#Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
#element and skipping one element in between.


def reverse_skip(lst):

    return lst[-2::-2]


print(reverse_skip([1,2,3,4,5,6]))

[5, 3, 1]


Nested List

In [34]:
#1. Flatten a Nested List:
#Write a Python function that takes a nested list and flattens it into a single list, where all the elements
#are in a single dimension.


def flatten(lst):

    flat_list = []
    for element in lst:
        if isinstance(element, list):
            flat_list.extend(flatten(element))
        else:
            flat_list.append(element)
    return flat_list

nested_list = [[1, 2], [3, 4], [5], [6, [7, 8]]]
print("Original nested list:", nested_list)
print("Flattened list:", flatten(nested_list))

Original nested list: [[1, 2], [3, 4], [5], [6, [7, 8]]]
Flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


In [35]:
#2. Accessing Nested List Elements:
# Write a Python function that extracts a specific element from a nested list given its indices.


def access_nested_element(lst, indices):

    current_element = lst
    for i, index in enumerate(indices):
        if isinstance(current_element, list) and 0 <= index < len(current_element):
            current_element = current_element[index]
        else:
            raise IndexError(f"Invalid index {index} at depth {i}. Path: {indices}")
    return current_element

lst1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices1 = [1, 2]
print(f"Original nested list: {lst1}")
print(f"Indices: {indices1}")
print(f"Extracted element: {access_nested_element(lst1, indices1)}")

lst2 = [[[1,2],[3,4]], [[5,6],[7,8]]]
indices2 = [1,0,1]
print(f"\nOriginal nested list: {lst2}")
print(f"Indices: {indices2}")
print(f"Extracted element: {access_nested_element(lst2, indices2)}")

try:

    print("\nTrying to access invalid index:")
    access_nested_element(lst1, [0, 5])
except IndexError as e:
    print(e)

Original nested list: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Indices: [1, 2]
Extracted element: 6

Original nested list: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Indices: [1, 0, 1]
Extracted element: 6

Trying to access invalid index:
Invalid index 5 at depth 1. Path: [0, 5]


In [36]:
#3. Sum of All Elements in a Nested List:
# Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).


def sum_nested(lst):

    total_sum = 0
    for element in lst:
        if isinstance(element, list):
            total_sum += sum_nested(element)
        elif isinstance(element, (int, float)):
            total_sum += element
    return total_sum

# Example usage:
nested_list_sum = [[1, 2], [3, [4, 5]], 6]
print(f"Original nested list: {nested_list_sum}")
print(f"Sum of all elements: {sum_nested(nested_list_sum)}")

Original nested list: [[1, 2], [3, [4, 5]], 6]
Sum of all elements: 21


In [37]:
#4. Remove Specific Element from a Nested List:
# Write a Python function that removes all occurrences of a specific element from a nested list.



def remove_element(lst, elem):

    new_list = []
    for item in lst:
        if isinstance(item, list):
            # Recursively process sublists
            processed_sublist = remove_element(item, elem)
            if processed_sublist:
                # Only add sublist if it's not empty after removal
                new_list.append(processed_sublist)
        elif item != elem:
            new_list.append(item)
    return new_list

# Example usage:
lst_remove = [[1, 2], [3, 2], [4, 5], 2, [6, [2, 7]]]
elem_to_remove = 2
print(f"Original nested list: {lst_remove}")
print(f"Element to remove: {elem_to_remove}")
print(f"List after removing '{elem_to_remove}': {remove_element(lst_remove, elem_to_remove)}")

Original nested list: [[1, 2], [3, 2], [4, 5], 2, [6, [2, 7]]]
Element to remove: 2
List after removing '2': [[1], [3], [4, 5], [6, [7]]]


In [38]:
#5. Find the Maximum Element in a Nested List:
# Write a Python function that finds the maximum element in a nested list (regardless of depth).


def find_max_nested(lst):

    max_val = float('-inf') # Initialize with negative infinity
    found_numeric = False

    for element in lst:
        if isinstance(element, list):
            sublist_max = find_max_nested(element)
            if sublist_max is not None: # Check if sublist contained any numeric values
                max_val = max(max_val, sublist_max)
                found_numeric = True
        elif isinstance(element, (int, float)):
            max_val = max(max_val, element)
            found_numeric = True

    return max_val if found_numeric else None

nested_list_max = [[1, 2], [3, [4, 5]], 6, [-1, [10, 0]]]
print(f"Original nested list: {nested_list_max}")
print(f"Maximum element: {find_max_nested(nested_list_max)}")

nested_list_max_2 = [[-5, -1], [-10, [-2, -3]]]
print(f"Original nested list: {nested_list_max_2}")
print(f"Maximum element: {find_max_nested(nested_list_max_2)}")

nested_list_empty = [[[]], []]
print(f"Original nested list: {nested_list_empty}")
print(f"Maximum element: {find_max_nested(nested_list_empty)}")

Original nested list: [[1, 2], [3, [4, 5]], 6, [-1, [10, 0]]]
Maximum element: 10
Original nested list: [[-5, -1], [-10, [-2, -3]]]
Maximum element: -1
Original nested list: [[[]], []]
Maximum element: None


In [58]:
#6. Count Occurrences of an Element in a Nested List:
#Write a Python function that counts how many times a specific element appears in a nested list.


def count_occurrences(lst, elem):

    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

# Example usage:
lst_count = [[1, 2], [2, 3], [2, 4], 2, [5, [2, 6, [2, 7]]]]
elem_to_count = 2
print(f"Original nested list: {lst_count}")
print(f"Element to count: {elem_to_count}")
print(f"Occurrences of '{elem_to_count}': {count_occurrences(lst_count, elem_to_count)}")

lst_count_str = [['a', 'b'], ['c', 'a'], 'd', ['a', ['e', 'a']]]
elem_to_count_str = 'a'
print(f"Original nested list: {lst_count_str}")
print(f"Element to count: {elem_to_count_str}")
print(f"Occurrences of '{elem_to_count_str}': {count_occurrences(lst_count_str, elem_to_count_str)}")

Original nested list: [[1, 2], [2, 3], [2, 4], 2, [5, [2, 6, [2, 7]]]]
Element to count: 2
Occurrences of '2': 6
Original nested list: [['a', 'b'], ['c', 'a'], 'd', ['a', ['e', 'a']]]
Element to count: a
Occurrences of 'a': 4


In [59]:
#7. Flatten a List of Lists of Lists:
# Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.


def deep_flatten(lst):

    flat_list = []
    for element in lst:
        if isinstance(element, list):
            flat_list.extend(deep_flatten(element))
        else:
            flat_list.append(element)
    return flat_list

# Example usage:
nested_list_deep = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print(f"Original deeply nested list: {nested_list_deep}")
print(f"Deeply flattened list: {deep_flatten(nested_list_deep)}")

nested_list_deep_2 = [1, [2, [3, 4], 5], 6, [7, [8, [9, 10]]]]
print(f"Original deeply nested list: {nested_list_deep_2}")
print(f"Deeply flattened list: {deep_flatten(nested_list_deep_2)}")

Original deeply nested list: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Deeply flattened list: [1, 2, 3, 4, 5, 6, 7, 8]
Original deeply nested list: [1, [2, [3, 4], 5], 6, [7, [8, [9, 10]]]]
Deeply flattened list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [60]:
#8. Nested List Average:
# Write a Python function that calculates the average of all elements in a nested list.



def average_nested(lst):

    elements = []
    def collect_numbers(sub_lst):
        for element in sub_lst:
            if isinstance(element, list):
                collect_numbers(element)
            elif isinstance(element, (int, float)):
                elements.append(element)

    collect_numbers(lst)

    if not elements:
        return 0 # Or raise an error, depending on desired behavior for empty/non-numeric lists

    return sum(elements) / len(elements)

# Example usage:
nested_list_avg = [[1, 2], [3, 4], [5, 6]]
print(f"Original nested list: {nested_list_avg}")
print(f"Average of all elements: {average_nested(nested_list_avg)}")

nested_list_avg_2 = [[10, [20, 30]], 40, [50, [60]]]
print(f"Original nested list: {nested_list_avg_2}")
print(f"Average of all elements: {average_nested(nested_list_avg_2)}")

nested_list_empty_avg = [[], ['a'], [{}]]
print(f"Original nested list: {nested_list_empty_avg}")
print(f"Average of all elements: {average_nested(nested_list_empty_avg)}")

Original nested list: [[1, 2], [3, 4], [5, 6]]
Average of all elements: 3.5
Original nested list: [[10, [20, 30]], 40, [50, [60]]]
Average of all elements: 35.0
Original nested list: [[], ['a'], [{}]]
Average of all elements: 0


NumPy


In [42]:
import numpy as np

In [43]:
#Problem - 1: Array Creation:
#Complete the following Tasks:
#1. Initialize an empty array with size 2X2.
#2. Initialize an all one array with size 4X2.
#3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
#4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
#5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
#6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}





# 1. Initialize an empty array with size 2x2
a = np.empty((2,2))
print("Empty array:\n", a)

# 2. Initialize an all one array with size 4x2
b = np.ones((4,2))
print("\nOnes array:\n", b)

# 3. Array filled with specific value
c = np.full((3,3), 7)
print("\nFull array:\n", c)

# 4. Zeros array with same shape as another array
d = np.zeros_like(c)
print("\nZeros like array:\n", d)

# 5. Ones array with same shape
e = np.ones_like(c)
print("\nOnes like array:\n", e)

# 6. Convert list to numpy array
new_list = [1,2,3,4]
f = np.array(new_list)
print("\nConverted array:", f)

Empty array:
 [[4.4e-323 4.9e-323]
 [5.4e-323 5.9e-323]]

Ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

Ones like array:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

Converted array: [1 2 3 4]


In [44]:
#Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
#Complete the following tasks:
#1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
#2. Create a 3X3 matrix with values ranging from 0 to 8.
#{Hint:look for np.reshape()}
#3. Create a 3X3 identity matrix.{Hint:np.eye()}
#4. Create a random array of size 30 and find the mean of the array.
#{Hint:check for np.random.random() and array.mean() function}
#5. Create a 10X10 array with random values and find the minimum and maximum values.
#6. Create a zero array of size 10 and replace 5th element with 1.
#7. Reverse an array arr = [1,2,0,0,4,0].
#8. Create a 2d array with 1 on border and 0 inside.
#9. Create a 8X8 matrix and fill it with a checkerboard pattern.





# 1. Array from 10 to 49
a = np.arange(10,50)
print(a)

# 2. 3x3 matrix with values 0-8
b = np.arange(9).reshape(3,3)
print("\n3x3 matrix:\n", b)

# 3. Identity matrix
c = np.eye(3)
print("\nIdentity matrix:\n", c)

# 4. Random array of size 30 and mean
d = np.random.random(30)
print("\nMean:", d.mean())

# 5. 10x10 random array min and max
e = np.random.random((10,10))
print("\nMinimum:", e.min())
print("Maximum:", e.max())

# 6. Zero array size 10 and replace 5th element
f = np.zeros(10)
f[4] = 1
print("\nModified array:", f)

# 7. Reverse array
arr = np.array([1,2,0,0,4,0])
print("\nReversed:", arr[::-1])

# 8. 2D array with border 1 and inside 0
g = np.ones((5,5))
g[1:-1,1:-1] = 0
print("\nBorder array:\n", g)

# 9. Checkerboard pattern 8x8
h = np.zeros((8,8),dtype=int)
h[1::2,::2] = 1
h[::2,1::2] = 1
print("\nCheckerboard:\n", h)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Mean: 0.4803879540042638

Minimum: 0.0033826621691335212
Maximum: 0.9933584653608564

Modified array: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed: [0 4 0 0 2 1]

Border array:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

Checkerboard:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [45]:
#Problem - 3: Array Operations:
# For the following arrays:
# x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
# v = np.array([9,10]) and w = np.array([11,12]);
# Complete all the task using numpy:
# 1. Add the two array.
# 2. Subtract the two array.
#3. Multiply the array with any integers of your choice.
#4. Find the square of each element of the array.
#5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
#6. Concatenate x(and)y along row and Concatenate v(and)w along column.
#{Hint:try np.concatenate() or np.vstack() functions.
#7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?





x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

# 1. Addition
print("Addition:\n", x + y)

# 2. Subtraction
print("\nSubtraction:\n", x - y)

# 3. Multiply by integer
print("\nMultiply by 3:\n", x * 3)

# 4. Square each element
print("\nSquare:\n", x**2)

# 5. Dot products
print("\nDot v and w:", np.dot(v,w))
print("Dot x and v:", np.dot(x,v))
print("Dot x and y:\n", np.dot(x,y))

# 6. Concatenate
print("\nRow concatenate:\n", np.concatenate((x,y), axis=0))
print("\nColumn concatenate:\n", np.concatenate((v,w), axis=0))

# 7. Concatenate x and v
# This will give error because x is 2D and v is 1D
# numpy requires same dimensions

Addition:
 [[ 6  8]
 [10 13]]

Subtraction:
 [[-4 -4]
 [-4 -3]]

Multiply by 3:
 [[ 3  6]
 [ 9 15]]

Square:
 [[ 1  4]
 [ 9 25]]

Dot v and w: 219
Dot x and v: [29 77]
Dot x and y:
 [[19 22]
 [50 58]]

Row concatenate:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Column concatenate:
 [ 9 10 11 12]


In [46]:
#Problem - 4: Matrix Operations:
# • For the following arrays:
# A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
# Prove following with Numpy:
# 1. Prove A.A−1 = I.
# 2. Prove AB ̸= BA.
# 3. Prove (AB)

# T = BTAT




A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)

print("A inverse:\n", A_inv)
print("\nA * A^-1:\n", I)

# 2. Prove AB ≠ BA
AB = np.dot(A,B)
BA = np.dot(B,A)

print("\nAB:\n", AB)
print("\nBA:\n", BA)

# 3. Prove (AB)^T = B^T A^T
left = np.transpose(np.dot(A,B))
right = np.dot(np.transpose(B), np.transpose(A))

print("\n(AB)^T:\n", left)
print("\nB^T A^T:\n", right)

A inverse:
 [[-2.    1.  ]
 [ 1.75 -0.75]]

A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

(AB)^T:
 [[23 51]
 [13 29]]

B^T A^T:
 [[23 51]
 [13 29]]


In [47]:
# • Solve the following system of Linear equation using Inverse Methods.

# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9




A = np.array([
    [2,-3,1],
    [1,-1,2],
    [3,1,-1]
])

B = np.array([-1,-3,9])

# Inverse method
A_inv = np.linalg.inv(A)

X = np.dot(A_inv,B)

print("Solution [x,y,z]:", X)

Solution [x,y,z]: [ 2.  1. -2.]


Experiment: How Fast is Numpy?

In [48]:
import time
import numpy as np

In [49]:
# 1. Element-wise Addition:
# • Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
# and Print the time taken for this operation.
# • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
# this operation.




size = 1000000

list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [list1[i] + list2[i] for i in range(size)]
print("Python list addition time:", time.time()-start)

# NumPy
a = np.arange(size)
b = np.arange(size)

start = time.time()
c = a + b
print("NumPy addition time:", time.time()-start)

Python list addition time: 0.12649893760681152
NumPy addition time: 0.008070707321166992


In [50]:
# 2. Element-wise Multiplication
# • Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
# Measure and Print the time taken for this operation.
# • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
# this operation.



start = time.time()
result = [list1[i] * list2[i] for i in range(size)]
print("Python multiplication time:", time.time()-start)

start = time.time()
c = a * b
print("NumPy multiplication time:", time.time()-start)

Python multiplication time: 0.16958236694335938
NumPy multiplication time: 0.00768733024597168


In [51]:
# 3. Dot Product
# • Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
# Print the time taken for this operation.
# • Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
# this operation.




start = time.time()
dot = sum(list1[i]*list2[i] for i in range(size))
print("Python dot product time:", time.time()-start)

start = time.time()
dot = np.dot(a,b)
print("NumPy dot product time:", time.time()-start)

Python dot product time: 0.1330244541168213
NumPy dot product time: 0.002472400665283203


In [52]:
# 4. Matrix Multiplication

# • Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
# sure and print the time taken for this operation.

# • Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
# Measure and print the time taken for this operation.



size = 100

A = np.random.rand(size,size)
B = np.random.rand(size,size)

start = time.time()
C = np.dot(A,B)
print("NumPy matrix multiplication:", time.time()-start)

NumPy matrix multiplication: 0.00197601318359375
